---
title: "data import"
author: "AimingLiu"
date: "9/17/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```


## Load in a dataset

```{r}
litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)
```

##load in the pups data

```{r}
pups_data = read_csv(file = "./data_import_examples/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
```

##Play with column parsing
```{r}
litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv")
 col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
```
 
 ##Read in an excel file...
```{r}
library(readxl)
mlb_data = read_excel(path = "./data_import_examples/mlb11.xlsx")
```

##Read in a SAS...
```{r}
library(haven)
pulse_data = read_sas("./data_import_examples/public_pulse_data.sas7bdat")
```



```{r}
select(litters_data,group,litter_number)
select(litters_data,group,litter_number,gd0_weight)
```
```{r}
filter(litters_data,group =="Mod8")

filter(litters_data, gd_of_birth == 20)

filter(litters_data,gd_of_birth < 20)

filter(litters_data,pups_born_alive < 6 ,group == "Con7")

filter(litters_data,group == "Con7"|group == "Con8")

#don't do filtter(litters_data,!is_na(gd0_weight))#
#do#
drop_na(litters_data,gd0_weight)
```
#Mutate
```{r}
mutate(litters_data,
       wt_gain = gd18_weight - gd0_weight,
       group = str_to_lower(group))
```
#Arrange
```{r}
arrange(litters_data,pups_born_alive)

arrange(litters_data,desc(pups_born_alive))

arrange(litters_data,pups_born_alive,gd0_weight)
```

```{r}
litters_data = 
  read_csv("./data_import_examples/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(wt_gain = gd18_weight - gd0_weight,
       group = str_to_lower(group)) %>%
  drop_na(gd0_weight)
```
